### ISSUE TITLE
Roadmap 201603

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#186]
This issue serves as an overview of the issues and priorities for abapGit going forward. The roadmap may change at any time. If you find other things more important or an issue is not on the list, feel free to pick it up and work on it.

Prioritized list:

- [X] [Next generation XML #188](https://github.com/larshp/abapGit/issues/188)
Dependency: none
~~Fixes: #176 #175~~

- [X] [Serializer origin #187](https://github.com/larshp/abapGit/issues/187)
~~Dependency: #188~~

- [x] [Master language in .abapgit #189](https://github.com/larshp/abapGit/issues/189)
~~Dependency: #188~~

- [x] [New configuration #129](https://github.com/larshp/abapGit/issues/129)
~~Dependency: #188~~

- [X] Staging/Folders #5 
~~Dependency: #188 + #129~~
Fixes: ~~#173 #168 #62 #47~~

Quick wins, smaller independent tasks:
- ~~diff - jump to next difference #180~~
- ~~add progress bar #159~~
- ~~table_add and table_read accept only STANDARD TABLE #148 (issue obsolete after #188)~~
- rebranching installed project #127
- TABL domain/data element references #126
- ~~feature to create new package in clone popup window #115~~

**Comment by mrsimpson** [comment]
How are packages / paths currently being handled? Is this ready for productive use?

**Comment by larshp** [comment]
progress on #129 see separate repository https://github.com/larshp/abapGit-per-test

**Comment by larshp** [comment]
done, yay :fireworks: :rose: 

will create new roadmap when time permits, and if needed
