### ISSUE TITLE
UI/UX wishlist

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#346]
Here are some ideas I have for the usability. For the discussion (needed/not needed) :)
- [X] 1) Finetune repo page - hide filelist (keeping an option to show it) (#347)
- [ ] 2) Directories: add a feature to group objects per type and display it properly (#280). 
- [X] 2.1) Can be also used to display objects per subpackage (to #371)
- [X] 3) Asset caching - move CSS and JS to external files (#374)
- [x] 3.1) Use webfont (octicons) instead of images - will remove image data clutter (#525)
- [ ] 3.2) Use github primer for styles - this is in fact complete UI redesign ... will remove most of styles from the code
- [x] 4) code highlighting for the diff page (probably with prism.js - it supports abap) (#443)
- [x] 5) Show differences that **will** be pulled - kind of stage page but for pull - will give more control over changes (potentially destructive ones) (might help #296, #413, #515 )
- [ ] 6) Some feature to **easily** convert existing github repository to abapGit one (from pure code or saplink) - not sure sure how it should look like, just as idea
- [ ] 7) Some integration with SAP dev IDE. Not sure how it should look like - but it should be a possibility to commit own changes directly from se80&Co. (Seems to be no native userexits/BADIs available)
- [x] 8) (Maybe) rewriting stage page as ALV dialog - should simplify handling of large number of objects. Actual for some big projects only though. Alternatively, adjust the page so that it is not re-rendered after each 'Add' - add some filtering features, js ... (#353)
- [ ] 9) Yet another potentially interesting feature is stashing
- [ ] 10) Tailored diff for tables and structures, discussed in #371

**Comment by larshp** [comment]
1: a long file list can seem overwhelming, but on the other hand, all interesting information is at the top of the page(after your diff at top change)

3: I'd like not to include code from other projects inside in the abapGit repository, a way to handle this is having the files served of a CDN, like https://github.com/larshp/abapGit/blob/f04d774e09b8ccc1086d67c0ec1fa5b962f33d93/src/zabapgit_page_branch_overview.prog.abap#L431
However we need to decide if this is okay or not for core functionallity

4: suggest just to lower case the abap code, then call the pretty printer with keywords upper case(see https://github.com/larshp/WABAP/blob/master/abap/zcl_wabap_pretty_printer.clas.abap), then we know all keywords in the code. And then perhaps add a few internals eg 'string', this would be quite easy and without external dependencies.

5: been thinking of something similar, to show a list of "conflicts" if local objects are modified

6: perhaps add some guides to the wiki? from SAPlink would be to import objects into system via SAPLink and then export it via abapGit

7: I think it will be difficult to add functionality in SE80 as it would require quite a few enhancements, it would be possible to build an Eclipse plugin(but I am skipping Eclipse for SAP development as a technology). 

I'm more heading in the direction of https://github.com/larshp/WABAP it will fully control the frontend and backend functionallity, with ability to update both(frontend and backend) at the same time(via abapGit), and rapid development/shipping often(via abapGit), while still being confident that it works across SAP versions. It is a crazy idea, but hey everything has to start somewhere. :hushed: 

8: problem is that the page jumps to the top after clicking a link? Perhaps we can organize the files in multiple columns, there is usually lots of leftover horizontal space on the page

**Comment by sbcgua** [comment]
1) Mmmm ... I think I'll make an html sample to show what I mean. My idea is to keep the view switchable so evertyone is satisfied.

3) I though about this a bit. CDN is a good option. Both primer and octicons are MIT licenced so should be OK from this perpective. Including the code to the project - that's what I actually intend to avoid: just refer CDNs from the html as an external resource or/AND cache octicons/primercss as local resource in W3MIME storage - both are available as releases at github which suposedly custpomized (I mean SSL) if abapGit is installed.

4) Good idea - I'll look into it. 

5) Exactly ! :)

6) Maybe... but that is not convenient enough. **As a user**, I have that mockup_loader repo - it is not in abapGit. I want to migrate it but when I'm starting to think how to do it (removing existing files, attaching repo, finetuning .abapGit to commit to some directory ...) - I really stop. **As a user** I want the red button to do it for me :) Not most high priority feature though, just as as far future feature :)

7) Yeap, wabap looks very interesting indeed :)

8) As an option. I'll think. BTW can we assume that IE10 is the lowest browser version supported? It supports some features which might be useful here.

**Comment by larshp** [comment]
3: the ABAP application server might not be connected to the internet, CDN works because it is downloaded from the frontend pc

8: it will require some investigation into how it can be handled. However I think it is difficult due to the way POST is handled vs. the HTML container

**Comment by sbcgua** [comment]
3) I know, I mean the server will be likely connected to github which is also a source of primer and octicons. Anyway both features are possible to backup each other. 

8) Mmm, what do you mean ?

**Comment by larshp** [comment]
8: just guessing it is difficult, as javascript might not work with the "sapevent:" stuff

4: highlighting of XML can probably also be implemented in ABAP

**Comment by sbcgua** [comment]
9) Yet another potentially interesting feature is stashing

**Comment by TheWirtschaftsmann** [comment]
It seems that task 4 can be closed now as the functionality for highlighting of ABAP and XML-source code were delivered:)

**Comment by larshp** [comment]
6: perhaps https://github.com/larshp/abap-transmogrify can be used

@sbcgua suggest closing this issue and creating a new up-to-date issue which can contain less information

**Comment by sbcgua** [comment]
agree.

P.S. 346 ... it was so long ago ...

**Comment by larshp** [comment]
yea, things have changed, also just need to get a better overview of the open issues
